"""SQLAlchemy ORM models for smARTmatch."""

# This file is generated by scrapers/generate_models.py
# Do not edit manually; edit db/init-production/01_schema_production.sql (and
# scrapers/generate_models.py for production hardening), then re-run the generator.

from __future__ import annotations

from datetime import date, datetime
from typing import List, Optional
from uuid import uuid4

from sqlalchemy import (
    ARRAY,
    JSON,
    Boolean,
    Date,
    Float,
    ForeignKey,
    Integer,
    SmallInteger,
    String,
    Text,
)
from sqlalchemy.dialects.postgresql import TIMESTAMP, UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship


class Base(DeclarativeBase):
    pass


class Artist(Base):
    __tablename__ = "artist"

    artist_id: Mapped[UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid4
    )
    complete_name: Mapped[str] = mapped_column(String(255), nullable=False)
    date_of_birth: Mapped[Optional[date]] = mapped_column(Date)
    date_of_death: Mapped[Optional[date]] = mapped_column(Date)
    place_of_birth: Mapped[Optional[UUID]] = mapped_column(
        UUID(as_uuid=True), ForeignKey("location.location_id", ondelete="SET NULL")
    )
    place_of_death: Mapped[Optional[UUID]] = mapped_column(
        UUID(as_uuid=True), ForeignKey("location.location_id", ondelete="SET NULL")
    )
    raw_data: Mapped[Optional[str]] = mapped_column(Text)
    gender: Mapped[Optional[str]] = mapped_column(String(20))
    period_of_activity: Mapped[Optional[str]] = mapped_column(String(255))
    preferred_name: Mapped[Optional[str]] = mapped_column(String(255))
    surname: Mapped[Optional[str]] = mapped_column(String(255))
    title_of_nobility: Mapped[Optional[str]] = mapped_column(String(255))
    profession: Mapped[Optional[str]] = mapped_column(Text)
    biographical_info: Mapped[Optional[str]] = mapped_column(Text)
    associated_country_ids: Mapped[List[UUID]] = mapped_column(
        ARRAY(UUID(as_uuid=True)), nullable=False, default=list
    )
    activity_place_ids: Mapped[List[UUID]] = mapped_column(
        ARRAY(UUID(as_uuid=True)), nullable=False, default=list
    )

    birth_location: Mapped[Optional["Location"]] = relationship(
        "Location", foreign_keys=[place_of_birth]
    )
    death_location: Mapped[Optional["Location"]] = relationship(
        "Location", foreign_keys=[place_of_death]
    )

    artist_name_variants: Mapped[List["ArtistNameVariants"]] = relationship(
        "ArtistNameVariants", overlaps="artist"
    )
    auction_artworks: Mapped[List["AuctionArtwork"]] = relationship(
        "AuctionArtwork", overlaps="artist"
    )


class ArtistNameVariants(Base):
    __tablename__ = "artist_name_variants"

    name_variant_id: Mapped[UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid4
    )
    artist_id: Mapped[Optional[UUID]] = mapped_column(
        UUID(as_uuid=True), ForeignKey("artist.artist_id", ondelete="CASCADE")
    )
    name_variant: Mapped[str] = mapped_column(String(255), nullable=False)

    artist: Mapped[Optional["Artist"]] = relationship(
        "Artist", foreign_keys=[artist_id]
    )


class ArtworkMatch(Base):
    __tablename__ = "artwork_match"

    match_id: Mapped[UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid4
    )
    lost_artwork_id: Mapped[UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("lost_artwork.lost_artwork_id", ondelete="CASCADE"),
        nullable=False,
    )
    auction_artwork_id: Mapped[UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("auction_artwork.auction_artwork_id", ondelete="CASCADE"),
        nullable=False,
    )
    final_score: Mapped[Optional[float]] = mapped_column(Float)
    confidence_score: Mapped[Optional[float]] = mapped_column(Float)
    match_date: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True), nullable=False, default=datetime.utcnow
    )
    matching_program: Mapped[UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("matching_program.matching_program_id", ondelete="CASCADE"),
        nullable=False,
    )
    visualization: Mapped[dict] = mapped_column(JSON, nullable=False, default=dict)
    rating: Mapped[Optional[int]] = mapped_column(SmallInteger)
    bookmarked: Mapped[Optional[bool]] = mapped_column(Boolean)
    archived: Mapped[Optional[bool]] = mapped_column(Boolean)

    lost_artwork: Mapped[Optional["LostArtwork"]] = relationship(
        "LostArtwork", foreign_keys=[lost_artwork_id]
    )
    auction_artwork: Mapped[Optional["AuctionArtwork"]] = relationship(
        "AuctionArtwork", foreign_keys=[auction_artwork_id]
    )
    matching_program_obj: Mapped[Optional["MatchingProgram"]] = relationship(
        "MatchingProgram", foreign_keys=[matching_program]
    )


class AuctionArtwork(Base):
    __tablename__ = "auction_artwork"

    auction_artwork_id: Mapped[UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid4
    )
    normalised_version: Mapped[Optional[int]] = mapped_column(Integer)
    title: Mapped[Optional[str]] = mapped_column(Text)
    title_en: Mapped[Optional[str]] = mapped_column(Text)
    artist_id: Mapped[Optional[UUID]] = mapped_column(
        UUID(as_uuid=True), ForeignKey("artist.artist_id", ondelete="SET NULL")
    )
    artist_full_name: Mapped[Optional[str]] = mapped_column(String(255))
    artist_birth_date: Mapped[Optional[date]] = mapped_column(Date)
    artist_death_date: Mapped[Optional[date]] = mapped_column(Date)
    artist_birth_place: Mapped[Optional[UUID]] = mapped_column(
        UUID(as_uuid=True), ForeignKey("location.location_id", ondelete="SET NULL")
    )
    artist_death_place: Mapped[Optional[UUID]] = mapped_column(
        UUID(as_uuid=True), ForeignKey("location.location_id", ondelete="SET NULL")
    )
    img_paths: Mapped[List[str]] = mapped_column(
        ARRAY(Text), nullable=False, default=list
    )
    width: Mapped[Optional[float]] = mapped_column(Float)
    height: Mapped[Optional[float]] = mapped_column(Float)
    width_frame: Mapped[Optional[float]] = mapped_column(Float)
    height_frame: Mapped[Optional[float]] = mapped_column(Float)
    dating: Mapped[Optional[str]] = mapped_column(String(255))
    dating_start: Mapped[Optional[int]] = mapped_column(SmallInteger)
    dating_end: Mapped[Optional[int]] = mapped_column(SmallInteger)
    description: Mapped[Optional[str]] = mapped_column(Text)
    description_en: Mapped[Optional[str]] = mapped_column(Text)
    auction_details: Mapped[Optional[dict]] = mapped_column(JSON)
    material: Mapped[Optional[str]] = mapped_column(String(255))
    material_en: Mapped[Optional[str]] = mapped_column(String(255))
    dict_material_name: Mapped[List[str]] = mapped_column(ARRAY(Text), default=list)
    technique: Mapped[Optional[str]] = mapped_column(String(255))
    technique_en: Mapped[Optional[str]] = mapped_column(String(255))
    dict_technique_name: Mapped[List[str]] = mapped_column(ARRAY(Text), default=list)
    provenance: Mapped[Optional[str]] = mapped_column(Text)
    provenance_en: Mapped[Optional[str]] = mapped_column(Text)
    auction_date: Mapped[Optional[date]] = mapped_column(Date)
    lot_id: Mapped[Optional[str]] = mapped_column(String(255))
    lot_url: Mapped[Optional[str]] = mapped_column(Text)
    auction_platform_id: Mapped[Optional[UUID]] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("auction_platform.auction_platform_id", ondelete="SET NULL"),
    )
    auctioneer_id: Mapped[Optional[UUID]] = mapped_column(
        UUID(as_uuid=True), ForeignKey("auctioneer.auctioneer_id", ondelete="SET NULL")
    )
    expert_id: Mapped[Optional[UUID]] = mapped_column(
        UUID(as_uuid=True), ForeignKey("expert.expert_id", ondelete="SET NULL")
    )
    condition: Mapped[Optional[str]] = mapped_column(Text)
    signature: Mapped[Optional[str]] = mapped_column(Text)
    literature: Mapped[Optional[str]] = mapped_column(Text)
    raw_data: Mapped[Optional[dict]] = mapped_column(JSON)
    artist_raw_data: Mapped[Optional[str]] = mapped_column(Text)
    date_of_birth_raw_data: Mapped[Optional[str]] = mapped_column(Text)
    date_of_death_raw_data: Mapped[Optional[str]] = mapped_column(Text)
    place_of_birth_raw_data: Mapped[Optional[str]] = mapped_column(Text)
    place_of_death_raw_data: Mapped[Optional[str]] = mapped_column(Text)
    dimensions_raw_data: Mapped[Optional[str]] = mapped_column(Text)

    artist: Mapped[Optional["Artist"]] = relationship(
        "Artist", foreign_keys=[artist_id]
    )
    artist_birth_place_obj: Mapped[Optional["Location"]] = relationship(
        "Location", foreign_keys=[artist_birth_place]
    )
    artist_death_place_obj: Mapped[Optional["Location"]] = relationship(
        "Location", foreign_keys=[artist_death_place]
    )
    auction_platform: Mapped[Optional["AuctionPlatform"]] = relationship(
        "AuctionPlatform", foreign_keys=[auction_platform_id]
    )
    auctioneer: Mapped[Optional["Auctioneer"]] = relationship(
        "Auctioneer", foreign_keys=[auctioneer_id]
    )
    expert: Mapped[Optional["Expert"]] = relationship(
        "Expert", foreign_keys=[expert_id]
    )

    artwork_matchs: Mapped[List["ArtworkMatch"]] = relationship(
        "ArtworkMatch", overlaps="auction_artwork"
    )
    match_scores: Mapped[List["MatchScore"]] = relationship(
        "MatchScore", overlaps="auction"
    )


class AuctionPlatform(Base):
    __tablename__ = "auction_platform"

    auction_platform_id: Mapped[UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid4
    )
    name: Mapped[str] = mapped_column(String(255), nullable=False)
    address: Mapped[Optional[str]] = mapped_column(String(255))
    phone: Mapped[Optional[str]] = mapped_column(String(50))
    email: Mapped[Optional[str]] = mapped_column(String(255))
    raw_data: Mapped[Optional[str]] = mapped_column(Text)

    auction_artworks: Mapped[List["AuctionArtwork"]] = relationship(
        "AuctionArtwork", overlaps="auction_platform"
    )


class Auctioneer(Base):
    __tablename__ = "auctioneer"

    auctioneer_id: Mapped[UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid4
    )
    name: Mapped[str] = mapped_column(String(255), nullable=False)
    address: Mapped[Optional[str]] = mapped_column(String(255))
    phone: Mapped[Optional[str]] = mapped_column(String(50))
    email: Mapped[Optional[str]] = mapped_column(String(255))
    raw_data: Mapped[Optional[str]] = mapped_column(Text)

    auction_artworks: Mapped[List["AuctionArtwork"]] = relationship(
        "AuctionArtwork", overlaps="auctioneer"
    )


class Contact(Base):
    __tablename__ = "contact"

    contact_id: Mapped[UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid4
    )
    first_name: Mapped[str] = mapped_column(String(255), nullable=False)
    last_name: Mapped[str] = mapped_column(String(255), nullable=False)
    role: Mapped[Optional[str]] = mapped_column(String(255))
    phone: Mapped[Optional[str]] = mapped_column(String(50))
    email: Mapped[Optional[str]] = mapped_column(String(255))
    institution_id: Mapped[Optional[UUID]] = mapped_column(
        UUID(as_uuid=True), ForeignKey("institution.institution_id", ondelete="CASCADE")
    )

    institution: Mapped[Optional["Institution"]] = relationship(
        "Institution", foreign_keys=[institution_id]
    )


class Country(Base):
    __tablename__ = "country"

    country_id: Mapped[UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid4
    )
    country_name: Mapped[str] = mapped_column(String(255), nullable=False)
    country_name_en: Mapped[Optional[str]] = mapped_column(String(255))


class DictMaterial(Base):
    __tablename__ = "dict_material"

    material_name: Mapped[str] = mapped_column(String(50), primary_key=True)
    material_parent: Mapped[Optional[str]] = mapped_column(
        String(50), ForeignKey("dict_material.material_name", ondelete="SET NULL")
    )

    material_parent_obj: Mapped[Optional["DictMaterial"]] = relationship(
        "DictMaterial", foreign_keys=[material_parent]
    )

    dict_materials: Mapped[List["DictMaterial"]] = relationship(
        "DictMaterial", overlaps="material_parent_obj"
    )
    material_variants: Mapped[List["MaterialVariant"]] = relationship(
        "MaterialVariant", overlaps="dict_material_name_obj"
    )
    normalization_materials: Mapped[List["NormalizationMaterial"]] = relationship(
        "NormalizationMaterial", overlaps="dict_material_name_obj"
    )


class DictTechnique(Base):
    __tablename__ = "dict_technique"

    technique_name: Mapped[str] = mapped_column(String(50), primary_key=True)
    technique_parent: Mapped[Optional[str]] = mapped_column(
        String(50), ForeignKey("dict_technique.technique_name", ondelete="SET NULL")
    )

    technique_parent_obj: Mapped[Optional["DictTechnique"]] = relationship(
        "DictTechnique", foreign_keys=[technique_parent]
    )

    dict_techniques: Mapped[List["DictTechnique"]] = relationship(
        "DictTechnique", overlaps="technique_parent_obj"
    )
    normalization_techniques: Mapped[List["NormalizationTechnique"]] = relationship(
        "NormalizationTechnique", overlaps="dict_technique_name_obj"
    )
    technique_variants: Mapped[List["TechniqueVariant"]] = relationship(
        "TechniqueVariant", overlaps="dict_technique_name_obj"
    )


class DictTitle(Base):
    __tablename__ = "dict_title"

    dict_title_id: Mapped[UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid4
    )
    title_name: Mapped[str] = mapped_column(String(255), nullable=False)
    title_score: Mapped[Optional[float]] = mapped_column(Float)


class Expert(Base):
    __tablename__ = "expert"

    expert_id: Mapped[UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid4
    )
    first_name: Mapped[str] = mapped_column(String(255), nullable=False)
    last_name: Mapped[str] = mapped_column(String(255), nullable=False)
    organization: Mapped[Optional[str]] = mapped_column(String(255))
    phone: Mapped[Optional[str]] = mapped_column(String(50))
    email: Mapped[Optional[str]] = mapped_column(String(255))
    raw_data: Mapped[Optional[str]] = mapped_column(Text)

    auction_artworks: Mapped[List["AuctionArtwork"]] = relationship(
        "AuctionArtwork", overlaps="expert"
    )


class Institution(Base):
    __tablename__ = "institution"

    institution_id: Mapped[UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid4
    )
    name: Mapped[str] = mapped_column(String(255), nullable=False)
    address: Mapped[Optional[str]] = mapped_column(String(255))
    phone: Mapped[Optional[str]] = mapped_column(String(50))
    fax: Mapped[Optional[str]] = mapped_column(String(50))
    website: Mapped[Optional[str]] = mapped_column(String(255))
    email: Mapped[Optional[str]] = mapped_column(String(255))
    contact_ids: Mapped[List[UUID]] = mapped_column(
        ARRAY(UUID(as_uuid=True)), default=list
    )
    raw_data: Mapped[Optional[str]] = mapped_column(Text)

    contacts: Mapped[List["Contact"]] = relationship("Contact", overlaps="institution")
    lost_artworks: Mapped[List["LostArtwork"]] = relationship(
        "LostArtwork", overlaps="institution"
    )


class LiteratureSource(Base):
    __tablename__ = "literature_source"

    literature_id: Mapped[UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid4
    )
    title: Mapped[str] = mapped_column(Text, nullable=False)
    author: Mapped[Optional[str]] = mapped_column(Text)
    publishing_date: Mapped[Optional[date]] = mapped_column(Date)
    publishing_location: Mapped[Optional[str]] = mapped_column(Text)
    raw_data: Mapped[Optional[str]] = mapped_column(Text)
    publishing_location_id: Mapped[Optional[UUID]] = mapped_column(
        UUID(as_uuid=True), ForeignKey("location.location_id", ondelete="SET NULL")
    )

    publishing_location: Mapped[Optional["Location"]] = relationship(
        "Location", foreign_keys=[publishing_location_id]
    )

    lost_artworks: Mapped[List["LostArtwork"]] = relationship(
        "LostArtwork", overlaps="literature_source"
    )


class Location(Base):
    __tablename__ = "location"

    location_id: Mapped[UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid4
    )
    location_name: Mapped[str] = mapped_column(String(255), nullable=False)
    location_name_en: Mapped[Optional[str]] = mapped_column(String(255))
    country: Mapped[Optional[str]] = mapped_column(String(255))
    country_en: Mapped[Optional[str]] = mapped_column(String(255))
    raw_data: Mapped[Optional[str]] = mapped_column(Text)
    lat: Mapped[Optional[float]] = mapped_column(Float)
    lon: Mapped[Optional[float]] = mapped_column(Float)
    historical_info: Mapped[Optional[str]] = mapped_column(Text)
    display_name: Mapped[Optional[str]] = mapped_column(Text)
    country_ids: Mapped[List[UUID]] = mapped_column(
        ARRAY(UUID(as_uuid=True)), nullable=False, default=list
    )

    artists_via_birth_location: Mapped[List["Artist"]] = relationship(
        "Artist", foreign_keys="[Artist.place_of_birth]", overlaps="birth_location"
    )
    artists_via_death_location: Mapped[List["Artist"]] = relationship(
        "Artist", foreign_keys="[Artist.place_of_death]", overlaps="death_location"
    )
    auction_artworks_via_artist_birth_place_obj: Mapped[List["AuctionArtwork"]] = (
        relationship(
            "AuctionArtwork",
            foreign_keys="[AuctionArtwork.artist_birth_place]",
            overlaps="artist_birth_place_obj",
        )
    )
    auction_artworks_via_artist_death_place_obj: Mapped[List["AuctionArtwork"]] = (
        relationship(
            "AuctionArtwork",
            foreign_keys="[AuctionArtwork.artist_death_place]",
            overlaps="artist_death_place_obj",
        )
    )
    literature_sources: Mapped[List["LiteratureSource"]] = relationship(
        "LiteratureSource", overlaps="publishing_location"
    )
    location_name_variants: Mapped[List["LocationNameVariants"]] = relationship(
        "LocationNameVariants", overlaps="location"
    )


class LocationNameVariants(Base):
    __tablename__ = "location_name_variants"

    name_variant_id: Mapped[UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid4
    )
    location_id: Mapped[UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("location.location_id", ondelete="CASCADE"),
        nullable=False,
    )
    name_variant: Mapped[str] = mapped_column(String(255), nullable=False)

    location: Mapped[Optional["Location"]] = relationship(
        "Location", foreign_keys=[location_id]
    )


class LostArtwork(Base):
    __tablename__ = "lost_artwork"

    lost_artwork_id: Mapped[UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid4
    )
    title: Mapped[Optional[str]] = mapped_column(Text)
    title_en: Mapped[Optional[str]] = mapped_column(Text)
    artist_ids: Mapped[List[UUID]] = mapped_column(
        ARRAY(UUID(as_uuid=True)), default=list
    )
    depicted_person_ids: Mapped[List[UUID]] = mapped_column(
        ARRAY(UUID(as_uuid=True)), nullable=False, default=list
    )
    img_paths: Mapped[List[str]] = mapped_column(
        ARRAY(Text), nullable=False, default=list
    )
    width: Mapped[Optional[float]] = mapped_column(Float)
    height: Mapped[Optional[float]] = mapped_column(Float)
    width_frame: Mapped[Optional[float]] = mapped_column(Float)
    height_frame: Mapped[Optional[float]] = mapped_column(Float)
    depth: Mapped[Optional[str]] = mapped_column(Text)
    diameter: Mapped[Optional[str]] = mapped_column(Text)
    dating: Mapped[Optional[str]] = mapped_column(String(255))
    dating_start: Mapped[Optional[int]] = mapped_column(SmallInteger)
    dating_end: Mapped[Optional[int]] = mapped_column(SmallInteger)
    description: Mapped[Optional[str]] = mapped_column(Text)
    description_en: Mapped[Optional[str]] = mapped_column(Text)
    inventory_number: Mapped[Optional[str]] = mapped_column(Text)
    material: Mapped[Optional[str]] = mapped_column(String(255))
    dict_material_name: Mapped[List[str]] = mapped_column(ARRAY(Text), default=list)
    technique: Mapped[Optional[str]] = mapped_column(String(255))
    dict_technique_name: Mapped[List[str]] = mapped_column(ARRAY(Text), default=list)
    provenance: Mapped[Optional[str]] = mapped_column(Text)
    provenance_en: Mapped[Optional[str]] = mapped_column(Text)
    institution_id: Mapped[Optional[UUID]] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("institution.institution_id", ondelete="SET NULL"),
    )
    circumstances_of_loss: Mapped[Optional[str]] = mapped_column(Text)
    lost_art_id: Mapped[Optional[str]] = mapped_column(String(255))
    lost_art_url: Mapped[Optional[str]] = mapped_column(String(255))
    keywords: Mapped[List[str]] = mapped_column(
        ARRAY(Text), nullable=False, default=list
    )
    literature_source_id: Mapped[Optional[UUID]] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("literature_source.literature_id", ondelete="SET NULL"),
    )
    literature_source_page: Mapped[Optional[int]] = mapped_column(SmallInteger)
    type_of_loss: Mapped[Optional[str]] = mapped_column(String(255))
    restituted: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    raw_data: Mapped[Optional[dict]] = mapped_column(JSON)
    location_history: Mapped[Optional[dict]] = mapped_column(JSON)

    institution: Mapped[Optional["Institution"]] = relationship(
        "Institution", foreign_keys=[institution_id]
    )
    literature_source: Mapped[Optional["LiteratureSource"]] = relationship(
        "LiteratureSource", foreign_keys=[literature_source_id]
    )

    artwork_matchs: Mapped[List["ArtworkMatch"]] = relationship(
        "ArtworkMatch", overlaps="lost_artwork"
    )
    lostart_artworks: Mapped[List["LostartArtwork"]] = relationship(
        "LostartArtwork", overlaps="lost_artwork"
    )
    match_scores: Mapped[List["MatchScore"]] = relationship(
        "MatchScore", overlaps="lost"
    )
    spsg_artworks: Mapped[List["SpsgArtwork"]] = relationship(
        "SpsgArtwork", overlaps="lost_artwork"
    )


class LostartArtwork(Base):
    __tablename__ = "lostart_artwork"

    lostart_artwork_id: Mapped[UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid4
    )
    title: Mapped[Optional[str]] = mapped_column(Text)
    artist_ids: Mapped[List[UUID]] = mapped_column(
        ARRAY(UUID(as_uuid=True)), default=list
    )
    depicted_person_ids: Mapped[List[UUID]] = mapped_column(
        ARRAY(UUID(as_uuid=True)), nullable=False, default=list
    )
    artist_raw_data: Mapped[Optional[str]] = mapped_column(Text)
    dimensions_raw_data: Mapped[Optional[str]] = mapped_column(Text)
    width: Mapped[Optional[float]] = mapped_column(Float)
    height: Mapped[Optional[float]] = mapped_column(Float)
    width_frame: Mapped[Optional[float]] = mapped_column(Float)
    height_frame: Mapped[Optional[float]] = mapped_column(Float)
    diameter: Mapped[Optional[float]] = mapped_column(Float)
    dating: Mapped[Optional[str]] = mapped_column(String(255))
    dating_start: Mapped[Optional[int]] = mapped_column(SmallInteger)
    dating_end: Mapped[Optional[int]] = mapped_column(SmallInteger)
    material: Mapped[Optional[str]] = mapped_column(String(255))
    dict_material_name: Mapped[List[str]] = mapped_column(ARRAY(Text), default=list)
    technique: Mapped[Optional[str]] = mapped_column(String(255))
    dict_technique_name: Mapped[List[str]] = mapped_column(ARRAY(Text), default=list)
    inventory_number: Mapped[Optional[str]] = mapped_column(Text)
    img_paths: Mapped[List[str]] = mapped_column(
        ARRAY(Text), nullable=False, default=list
    )
    lost_artwork_id: Mapped[Optional[UUID]] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("lost_artwork.lost_artwork_id", ondelete="SET NULL"),
    )

    lost_artwork: Mapped[Optional["LostArtwork"]] = relationship(
        "LostArtwork", foreign_keys=[lost_artwork_id]
    )

    match_score_testsets: Mapped[List["MatchScoreTestset"]] = relationship(
        "MatchScoreTestset", overlaps="lostart_artwork"
    )
    test_pairs: Mapped[List["TestPair"]] = relationship(
        "TestPair", overlaps="lostart_artwork"
    )


class MatchScore(Base):
    __tablename__ = "match_score"

    match_id: Mapped[UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid4
    )
    lost_id: Mapped[UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("lost_artwork.lost_artwork_id", ondelete="CASCADE"),
        nullable=False,
    )
    auction_id: Mapped[UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("auction_artwork.auction_artwork_id", ondelete="CASCADE"),
        nullable=False,
    )
    title_sim: Mapped[Optional[float]] = mapped_column(Float)
    artist_sim: Mapped[Optional[float]] = mapped_column(Float)
    dating_sim: Mapped[Optional[float]] = mapped_column(Float)
    dimensions_sim: Mapped[Optional[float]] = mapped_column(Float)
    material_sim: Mapped[Optional[float]] = mapped_column(Float)
    technique_sim: Mapped[Optional[float]] = mapped_column(Float)
    final_score: Mapped[Optional[float]] = mapped_column(Float)
    confidence_score: Mapped[Optional[float]] = mapped_column(Float)
    created_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True), nullable=False, default=datetime.utcnow
    )
    matching_program: Mapped[UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("matching_program.matching_program_id", ondelete="CASCADE"),
        nullable=False,
    )

    lost: Mapped[Optional["LostArtwork"]] = relationship(
        "LostArtwork", foreign_keys=[lost_id]
    )
    auction: Mapped[Optional["AuctionArtwork"]] = relationship(
        "AuctionArtwork", foreign_keys=[auction_id]
    )
    matching_program_obj: Mapped[Optional["MatchingProgram"]] = relationship(
        "MatchingProgram", foreign_keys=[matching_program]
    )


class MatchScoreTestset(Base):
    __tablename__ = "match_score_testset"

    match_id: Mapped[UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid4
    )
    lostart_artwork_id: Mapped[UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("lostart_artwork.lostart_artwork_id", ondelete="CASCADE"),
        nullable=False,
    )
    spsg_artwork_id: Mapped[UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("spsg_artwork.spsg_artwork_id", ondelete="CASCADE"),
        nullable=False,
    )
    title_sim: Mapped[Optional[float]] = mapped_column(Float)
    artist_sim: Mapped[Optional[float]] = mapped_column(Float)
    dating_sim: Mapped[Optional[float]] = mapped_column(Float)
    dimensions_sim: Mapped[Optional[float]] = mapped_column(Float)
    material_sim: Mapped[Optional[float]] = mapped_column(Float)
    technique_sim: Mapped[Optional[float]] = mapped_column(Float)
    final_score: Mapped[Optional[float]] = mapped_column(Float)
    confidence_score: Mapped[Optional[float]] = mapped_column(Float)
    created_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True), nullable=False, default=datetime.utcnow
    )
    matching_program: Mapped[UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("matching_program.matching_program_id", ondelete="CASCADE"),
        nullable=False,
    )
    is_match: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)

    lostart_artwork: Mapped[Optional["LostartArtwork"]] = relationship(
        "LostartArtwork", foreign_keys=[lostart_artwork_id]
    )
    spsg_artwork: Mapped[Optional["SpsgArtwork"]] = relationship(
        "SpsgArtwork", foreign_keys=[spsg_artwork_id]
    )
    matching_program_obj: Mapped[Optional["MatchingProgram"]] = relationship(
        "MatchingProgram", foreign_keys=[matching_program]
    )


class MatchingProgram(Base):
    __tablename__ = "matching_program"

    matching_program_id: Mapped[UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid4
    )
    name: Mapped[str] = mapped_column(String(50), nullable=False)
    version: Mapped[str] = mapped_column(String(50), nullable=False)
    description: Mapped[Optional[str]] = mapped_column(Text)

    artwork_matchs: Mapped[List["ArtworkMatch"]] = relationship(
        "ArtworkMatch", overlaps="matching_program_obj"
    )
    match_scores: Mapped[List["MatchScore"]] = relationship(
        "MatchScore", overlaps="matching_program_obj"
    )
    match_score_testsets: Mapped[List["MatchScoreTestset"]] = relationship(
        "MatchScoreTestset", overlaps="matching_program_obj"
    )


class MaterialVariant(Base):
    __tablename__ = "material_variant"

    material_variant_id: Mapped[UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid4
    )
    dict_material_name: Mapped[str] = mapped_column(
        String(50),
        ForeignKey("dict_material.material_name", ondelete="CASCADE"),
        nullable=False,
    )
    material_raw_data: Mapped[str] = mapped_column(String(50), nullable=False)
    match_type: Mapped[str] = mapped_column(String(50), nullable=False)

    dict_material_name_obj: Mapped[Optional["DictMaterial"]] = relationship(
        "DictMaterial", foreign_keys=[dict_material_name]
    )


class NormalizationMaterial(Base):
    __tablename__ = "normalization_material"

    normalization_material_id: Mapped[UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid4
    )
    dict_material_name: Mapped[str] = mapped_column(
        String(50),
        ForeignKey("dict_material.material_name", ondelete="CASCADE"),
        nullable=False,
    )
    material_raw_data: Mapped[str] = mapped_column(String(50), nullable=False)
    match_type: Mapped[str] = mapped_column(String(50), nullable=False)

    dict_material_name_obj: Mapped[Optional["DictMaterial"]] = relationship(
        "DictMaterial", foreign_keys=[dict_material_name]
    )


class NormalizationTechnique(Base):
    __tablename__ = "normalization_technique"

    normalization_technique_id: Mapped[UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid4
    )
    dict_technique_name: Mapped[str] = mapped_column(
        String(50),
        ForeignKey("dict_technique.technique_name", ondelete="CASCADE"),
        nullable=False,
    )
    technique_raw_data: Mapped[str] = mapped_column(String(50), nullable=False)
    match_type: Mapped[str] = mapped_column(String(50), nullable=False)

    dict_technique_name_obj: Mapped[Optional["DictTechnique"]] = relationship(
        "DictTechnique", foreign_keys=[dict_technique_name]
    )


class ScraperRun(Base):
    __tablename__ = "scraper_run"

    run_id: Mapped[UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid4
    )
    scraper_name: Mapped[str] = mapped_column(String(100), nullable=False)
    status: Mapped[str] = mapped_column(String(20), nullable=False)
    started_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True), nullable=False, default=datetime.utcnow
    )
    finished_at: Mapped[Optional[datetime]] = mapped_column(TIMESTAMP(timezone=True))
    entries_scraped: Mapped[int] = mapped_column(Integer, nullable=False)
    entries_skipped: Mapped[int] = mapped_column(Integer, nullable=False)
    total_entries: Mapped[int] = mapped_column(Integer, nullable=False)
    error_message: Mapped[Optional[str]] = mapped_column(Text)


class SpsgArtwork(Base):
    __tablename__ = "spsg_artwork"

    spsg_artwork_id: Mapped[UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid4
    )
    title: Mapped[Optional[str]] = mapped_column(Text)
    artist_ids: Mapped[List[UUID]] = mapped_column(
        ARRAY(UUID(as_uuid=True)), default=list
    )
    depicted_person_ids: Mapped[List[UUID]] = mapped_column(
        ARRAY(UUID(as_uuid=True)), nullable=False, default=list
    )
    artist_raw_data: Mapped[Optional[str]] = mapped_column(Text)
    dimensions_raw_data: Mapped[Optional[str]] = mapped_column(Text)
    width: Mapped[Optional[float]] = mapped_column(Float)
    height: Mapped[Optional[float]] = mapped_column(Float)
    width_frame: Mapped[Optional[float]] = mapped_column(Float)
    height_frame: Mapped[Optional[float]] = mapped_column(Float)
    diameter: Mapped[Optional[float]] = mapped_column(Float)
    dating: Mapped[Optional[str]] = mapped_column(String(255))
    dating_start: Mapped[Optional[int]] = mapped_column(SmallInteger)
    dating_end: Mapped[Optional[int]] = mapped_column(SmallInteger)
    material: Mapped[Optional[str]] = mapped_column(String(255))
    dict_material_name: Mapped[List[str]] = mapped_column(ARRAY(Text), default=list)
    technique: Mapped[Optional[str]] = mapped_column(String(255))
    dict_technique_name: Mapped[List[str]] = mapped_column(ARRAY(Text), default=list)
    inventory_number: Mapped[Optional[str]] = mapped_column(Text)
    img_paths: Mapped[List[str]] = mapped_column(
        ARRAY(Text), nullable=False, default=list
    )
    lost_artwork_id: Mapped[Optional[UUID]] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("lost_artwork.lost_artwork_id", ondelete="SET NULL"),
    )

    lost_artwork: Mapped[Optional["LostArtwork"]] = relationship(
        "LostArtwork", foreign_keys=[lost_artwork_id]
    )

    match_score_testsets: Mapped[List["MatchScoreTestset"]] = relationship(
        "MatchScoreTestset", overlaps="spsg_artwork"
    )
    test_pairs: Mapped[List["TestPair"]] = relationship(
        "TestPair", overlaps="spsg_artwork"
    )


class TechniqueVariant(Base):
    __tablename__ = "technique_variant"

    technique_variant_id: Mapped[UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid4
    )
    dict_technique_name: Mapped[str] = mapped_column(
        String(50),
        ForeignKey("dict_technique.technique_name", ondelete="CASCADE"),
        nullable=False,
    )
    technique_raw_data: Mapped[str] = mapped_column(String(50), nullable=False)
    match_type: Mapped[str] = mapped_column(String(50), nullable=False)

    dict_technique_name_obj: Mapped[Optional["DictTechnique"]] = relationship(
        "DictTechnique", foreign_keys=[dict_technique_name]
    )


class TestPair(Base):
    __tablename__ = "test_pair"

    test_pair_id: Mapped[UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid4
    )
    testset_id: Mapped[UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("testset.testset_id", ondelete="CASCADE"),
        nullable=False,
    )
    spsg_artwork_id: Mapped[UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("spsg_artwork.spsg_artwork_id", ondelete="CASCADE"),
        nullable=False,
    )
    lostart_artwork_id: Mapped[UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("lostart_artwork.lostart_artwork_id", ondelete="CASCADE"),
        nullable=False,
    )
    is_real_match: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)

    testset: Mapped[Optional["Testset"]] = relationship(
        "Testset", foreign_keys=[testset_id]
    )
    spsg_artwork: Mapped[Optional["SpsgArtwork"]] = relationship(
        "SpsgArtwork", foreign_keys=[spsg_artwork_id]
    )
    lostart_artwork: Mapped[Optional["LostartArtwork"]] = relationship(
        "LostartArtwork", foreign_keys=[lostart_artwork_id]
    )


class Testset(Base):
    __tablename__ = "testset"

    testset_id: Mapped[UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid4
    )
    name: Mapped[str] = mapped_column(String(255), nullable=False)
    description: Mapped[Optional[str]] = mapped_column(Text)
    created_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True), nullable=False, default=datetime.utcnow
    )

    test_pairs: Mapped[List["TestPair"]] = relationship("TestPair", overlaps="testset")
