-- Seed production with a compact, known-good image- and metadata-matching dataset.
--
-- The first ten pairs keep the pipeline_test_set image links used by the image
-- matching startup checks. All twelve pairs carry catalogue-style descriptions
-- adapted from the project pipeline integrity dataset.
-- Lost artwork rows keep the extracted metadata fields. Auction artwork rows
-- keep the raw catalogue description and auction/file metadata only, leaving
-- extracted fields empty for the metadata-extraction pipeline.
-- The final two pairs are metadata-only seed examples and intentionally do not
-- create image_file links.

DROP TABLE IF EXISTS pg_temp.pipeline_seed_pair;
CREATE TEMP TABLE pipeline_seed_pair (
    seed_key text NOT NULL,
    class_label text NOT NULL,
    metadata_testset_row integer NOT NULL,
    lost_artwork_id uuid NOT NULL,
    auction_artwork_id uuid NOT NULL,
    title text NOT NULL,
    artist_full_name text NOT NULL,
    dating text,
    dating_start smallint,
    dating_end smallint,
    width_cm real NOT NULL,
    height_cm real NOT NULL,
    dimensions_label text NOT NULL,
    material text NOT NULL,
    technique text NOT NULL,
    lost_description text NOT NULL,
    auction_description text NOT NULL,
    provenance text,
    signature text,
    condition text,
    literature text,
    lost_source_file_id text,
    lost_source_image_file_class_id integer,
    lost_source_tags text,
    lost_image_path text,
    auction_source_file_id text,
    auction_source_image_file_class_id integer,
    auction_source_tags text,
    auction_image_path text,
    lost_art_id text NOT NULL,
    inventory_number text NOT NULL,
    lot_id text NOT NULL,
    auction_date date NOT NULL
);

INSERT INTO pipeline_seed_pair (
    seed_key,
    class_label,
    metadata_testset_row,
    lost_artwork_id,
    auction_artwork_id,
    title,
    artist_full_name,
    dating,
    dating_start,
    dating_end,
    width_cm,
    height_cm,
    dimensions_label,
    material,
    technique,
    lost_description,
    auction_description,
    provenance,
    signature,
    condition,
    literature,
    lost_source_file_id,
    lost_source_image_file_class_id,
    lost_source_tags,
    lost_image_path,
    auction_source_file_id,
    auction_source_image_file_class_id,
    auction_source_tags,
    auction_image_path,
    lost_art_id,
    inventory_number,
    lot_id,
    auction_date
)
VALUES
    (
        'Q167605',
        'Q167605',
        4,
        uuid_generate_v5(uuid_ns_url(), 'https://smartmatch.invalid/pipeline-seed/lost/Q167605'),
        uuid_generate_v5(uuid_ns_url(), 'https://smartmatch.invalid/pipeline-seed/auction/Q167605'),
        'Erotische Darstellung von Peter Fendi, aus der Pseudologica Serie',
        'Arnulf Rainer',
        'um 1987',
        1987,
        1987,
        24.5,
        16.0,
        '24,5 x 16 cm',
        'Druck auf Papier, auf Papier kaschiert',
        'Mischtechnik',
        $$Verlustregister: Arnulf Rainer (Baden 1929), Erotische Darstellung von Peter Fendi, aus der Pseudologica Serie. Mischtechnik auf Druck auf Papier, auf Papier kaschiert, 24,5 x 16 cm, um 1987; rechts unten signiert A. Rainer. Provenienz: Privatsammlung Wien.$$,
        $$Auktionskatalog: Erotische Darstellung von Peter Fendi, aus der Pseudologica Serie von Arnulf Rainer, Baden 1929. Um 1987 entstandene Mischtechnik über Druck auf Papier, auf Papier kaschiert; Maße 24,5 x 16 cm. Signatur rechts unten: A. Rainer. Provenienz Privatsammlung Wien.$$,
        'Privatsammlung Wien',
        'Rechts unten signiert: A. Rainer',
        NULL,
        'vgl. „Arnulf Rainer fissa Peter Fendi – Pseudologica“ Hrsg. Peter Gorsen, Mailand 1989',
        'The Netherland galleries - being a history of the Dutch school of painting, illuminated and demonstrated by critical descriptions of the great paintings in the many galleries (1912) (14784164802)',
        4494,
        'frame_included,historic',
        'db/images/pipeline_test_set/Q167605_historic.jpg',
        'WLANL - Ritanila - IMG 2678',
        4946,
        'modern',
        'db/images/pipeline_test_set/Q167605_modern.jpg',
        'PIPELINE-LOST-Q167605',
        'PIPELINE-INV-01',
        'PIPELINE-AUCTION-Q167605',
        '2026-02-01'::date
    ),
    (
        'Q275349',
        'Q275349',
        5,
        uuid_generate_v5(uuid_ns_url(), 'https://smartmatch.invalid/pipeline-seed/lost/Q275349'),
        uuid_generate_v5(uuid_ns_url(), 'https://smartmatch.invalid/pipeline-seed/auction/Q275349'),
        'Gischtsäer',
        'Christian Ludwig Attersee',
        '2004',
        2004,
        2004,
        44.0,
        31.0,
        '44 x 31 cm',
        'Papier',
        'Mischtechnik',
        $$Suchdatensatz: Christian Ludwig Attersee (Pressburg 1940), Gischtsäer, Mischtechnik auf Papier, 44 x 31 cm. Das Blatt ist 2004 rechts unten signiert, datiert und betitelt: Attersee 04 Gischtsäer. Provenienz: Privatsammlung Wien.$$,
        $$Katalogeintrag für Christian Ludwig Attersee, geboren 1940 in Pressburg: Gischtsäer. Mischtechnik auf Papier; Maße 44 x 31 cm. Rechts unten mit Signatur, Datierung und Titel Attersee 04 Gischtsäer. Aus einer Privatsammlung Wien.$$,
        'Privatsammlung Wien',
        'Rechts unten signiert, datiert und betitelt: Attersee 04 Gischtsäer',
        NULL,
        NULL,
        'Vandalized Rokeby Venus 1914',
        4774,
        'historic,occluded',
        'db/images/pipeline_test_set/Q275349_historic.jpg',
        'Venus del Espejo de Diego Velázquez, Galería Nacional, Londres, Inglaterra, 2014-08-11, DD 176',
        4807,
        'frame_included,modern',
        'db/images/pipeline_test_set/Q275349_modern.jpg',
        'PIPELINE-LOST-Q275349',
        'PIPELINE-INV-02',
        'PIPELINE-AUCTION-Q275349',
        '2026-02-02'::date
    ),
    (
        'Q2741541',
        'Q2741541',
        6,
        uuid_generate_v5(uuid_ns_url(), 'https://smartmatch.invalid/pipeline-seed/lost/Q2741541'),
        uuid_generate_v5(uuid_ns_url(), 'https://smartmatch.invalid/pipeline-seed/auction/Q2741541'),
        'Ohne Titel',
        'Gottfried Fabian',
        '1966',
        1966,
        1966,
        44.0,
        33.0,
        '44 x 33 cm',
        'Platte',
        'Mischtechnik',
        $$Verlustnotiz: Gottfried Fabian (Dresden 1905 - 1984 Voitsberg), Ohne Titel. Mischtechnik auf Platte, 44 x 33 cm, datiert 1966. Links unten signiert und datiert Fabian 66, an der Oberkante nummeriert 821. Provenienz: Ausstellung Steiermark.$$,
        $$Auktionstext: Ohne Titel von Gottfried Fabian, Dresden 1905 bis 1984 Voitsberg. Die Mischtechnik auf Platte misst 44 x 33 cm und entstand 1966. Signatur und Datum links unten: Fabian 66; oben Nummer 821. Herkunft: Ausstellung Steiermark.$$,
        'Ausstellung Steiermark',
        'Links unten signiert und datiert: Fabian 66; an der Oberkante nummeriert: 821',
        NULL,
        NULL,
        'O Retablo de Monforte, de Hugo van der Goes, en Vida Gallega, 1910',
        3390,
        'frame_included,historic,poor_quality',
        'db/images/pipeline_test_set/Q2741541_historic.jpg',
        'Hugo van der Goes (Gand, 1440 circa – Auderghem, 1482) Altare Monforte - Adorazione dei Magi (1470 circa) - Tecnica olio su tavola Dimensioni 147×242 cm - Gemäldegalerie, Berlin',
        2335,
        'modern',
        'db/images/pipeline_test_set/Q2741541_modern.jpg',
        'PIPELINE-LOST-Q2741541',
        'PIPELINE-INV-03',
        'PIPELINE-AUCTION-Q2741541',
        '2026-02-03'::date
    ),
    (
        'Q3842726',
        'Q3842726',
        7,
        uuid_generate_v5(uuid_ns_url(), 'https://smartmatch.invalid/pipeline-seed/lost/Q3842726'),
        uuid_generate_v5(uuid_ns_url(), 'https://smartmatch.invalid/pipeline-seed/auction/Q3842726'),
        'Ohne Titel',
        'Peter Marquant',
        '2020',
        2020,
        2020,
        90.0,
        70.0,
        '90 x 70 cm',
        'Leinwand',
        'Öl',
        $$Suchmeldung: Peter Marquant (Wien 1954), Ohne Titel, Öl auf Leinwand, 90 x 70 cm, 2020. Rückseitig signiert und datiert Marquant 2020. Zustandshinweis: Krakelee und an der rechten Seite leichter Farbabrieb. Provenienz: Privatbesitz Wien.$$,
        $$Losbeschreibung: Ohne Titel von Peter Marquant, geboren 1954 in Wien. Öl auf Leinwand, Format 90 x 70 cm, datiert 2020. Verso signiert und datiert Marquant 2020; mit Krakelee sowie leichtem Farbabrieb rechts. Aus Privatbesitz Wien.$$,
        'Privatbesitz Wien',
        'Rückseitig signiert und datiert: Marquant 2020',
        'Krakelee, an der rechten Seite leichter Farbabrieb.',
        NULL,
        'PT-Pistoia-1909-Cattedrale-Vergine-in-trono',
        3491,
        'historic,poor_quality',
        'db/images/pipeline_test_set/Q3842726_historic.jpg',
        'Andrea del verrocchio e lorenzo di credi, madonna di piazza, 1475-86 ca. (pistoia, duomo) 02',
        440,
        'frame_included,modern',
        'db/images/pipeline_test_set/Q3842726_modern.jpg',
        'PIPELINE-LOST-Q3842726',
        'PIPELINE-INV-04',
        'PIPELINE-AUCTION-Q3842726',
        '2026-02-04'::date
    ),
    (
        'Q16169050',
        'Q16169050',
        8,
        uuid_generate_v5(uuid_ns_url(), 'https://smartmatch.invalid/pipeline-seed/lost/Q16169050'),
        uuid_generate_v5(uuid_ns_url(), 'https://smartmatch.invalid/pipeline-seed/auction/Q16169050'),
        'Meine beste Freundin Flaffy',
        'Saša Makarová',
        '2002',
        2002,
        2002,
        59.5,
        42.0,
        '59,5 x 42 cm',
        'Papier',
        'Öl und Bleistift',
        $$Verlustakte: Saša Makarová (Kosice 1966), Meine beste Freundin Flaffy. Öl und Bleistift auf Papier, 59,5 x 42 cm, entstanden 2002. Rückseitig signiert, datiert, nummeriert und betitelt Saša Makarová 2002 Meine beste Freundin Flaffy 2. Die rechte untere Blattecke weist eine Fehlstelle auf. Provenienz: Privatbesitz Wien.$$,
        $$Katalogfassung: Meine beste Freundin Flaffy von Saša Makarová, geboren 1966 in Kosice. Arbeit in Öl und Bleistift auf Papier, 59,5 x 42 cm, 2002. Verso mit Signatur, Datum, Nummer und Titel Saša Makarová 2002 Meine beste Freundin Flaffy 2; unten rechts Fehlstelle am Blatt. Provenienz Privatbesitz Wien.$$,
        'Privatbesitz Wien',
        'Rückseitig signiert, datiert, nummeriert und betitelt: Saša Makarová 2002 Meine beste Freundin Flaffy 2',
        'Die rechte untere Blattecke weist eine Fehlstelle auf.',
        NULL,
        'A partial bibliography of Dutch painters and their works - covering Cuyp, Dou, Hals, Hobbema, Rembrandt, Ruisdael and Wouwermann (1904) (14786532443)',
        222,
        'historic',
        'db/images/pipeline_test_set/Q16169050_historic.jpg',
        'WLANL - legalizefreedom - Banket van de officieren van de Cluveniersdoelen, 1627',
        4964,
        'modern',
        'db/images/pipeline_test_set/Q16169050_modern.jpg',
        'PIPELINE-LOST-Q16169050',
        'PIPELINE-INV-05',
        'PIPELINE-AUCTION-Q16169050',
        '2026-02-05'::date
    ),
    (
        'Q151047',
        'Q151047',
        9,
        uuid_generate_v5(uuid_ns_url(), 'https://smartmatch.invalid/pipeline-seed/lost/Q151047'),
        uuid_generate_v5(uuid_ns_url(), 'https://smartmatch.invalid/pipeline-seed/auction/Q151047'),
        'Ein alltäglicher Tag',
        'Drago J. Prelog',
        '1979',
        1979,
        1979,
        28.0,
        40.5,
        '28 x 40,5 cm (Passepartout-Ausschnitt)',
        'Papier',
        'Aquarell und Feder',
        $$Verlustbeschreibung: Drago J. Prelog (Cilli 1939 - 2020 Wien), Ein alltäglicher Tag. Aquarell und Feder auf Papier, 28 x 40,5 cm im Passepartout-Ausschnitt, datiert 1979. Rechts unten signiert, datiert und betitelt Drago J. Prelog 28. Mai 1979 ein alltäglicher Tag; links unten gewidmet. Provenienz: Galerie Gabriel Wien, Privatsammlung Wien.$$,
        $$Auktionslos: Ein alltäglicher Tag von Drago J. Prelog, Cilli 1939 bis 2020 Wien. Aquarell und Feder auf Papier, Passepartoutmaß 28 x 40,5 cm, 1979. Unten rechts signiert, datiert und mit Titel Drago J. Prelog 28. Mai 1979 ein alltäglicher Tag, links unten mit Widmung. Herkunft Galerie Gabriel Wien und Privatsammlung Wien.$$,
        'Galerie Gabriel Wien, Privatsammlung Wien',
        'Rechts unten signiert, datiert und betitelt: Drago J. Prelog 28. Mai 1979 ein alltäglicher Tag; links unten gewidmet',
        NULL,
        NULL,
        'Gazette des beaux-arts (1859) (14760118791)',
        2014,
        'historic',
        'db/images/pipeline_test_set/Q151047_historic.jpg',
        'Firenze 1006 43',
        1786,
        'frame_included,modern',
        'db/images/pipeline_test_set/Q151047_modern.jpg',
        'PIPELINE-LOST-Q151047',
        'PIPELINE-INV-06',
        'PIPELINE-AUCTION-Q151047',
        '2026-02-06'::date
    ),
    (
        'Q549847',
        'Q549847',
        10,
        uuid_generate_v5(uuid_ns_url(), 'https://smartmatch.invalid/pipeline-seed/lost/Q549847'),
        uuid_generate_v5(uuid_ns_url(), 'https://smartmatch.invalid/pipeline-seed/auction/Q549847'),
        'Ohne Titel',
        'Jürgen Messensee',
        '1984',
        1984,
        1984,
        54.0,
        40.5,
        '54 x 40,5 cm',
        'Papier',
        'Gouache',
        $$Suchregister: Jürgen Messensee (Wien 1936 - 2024 Wien), Ohne Titel. Gouache auf Papier, 54 x 40,5 cm, ungerahmt, 1984. Links oben signiert und datiert Messensee 84. Provenienz: Privatbesitz Niederlande.$$,
        $$Katalogtext: Ohne Titel von Jürgen Messensee, Wien 1936 bis 2024 Wien. Gouache auf Papier, ungerahmt, Maße 54 x 40,5 cm; entstanden 1984. Die Signatur und Datierung Messensee 84 befinden sich links oben. Provenienz Privatbesitz Niederlande.$$,
        'Privatbesitz Niederlande',
        'Links oben signiert und datiert: Messensee 84',
        NULL,
        NULL,
        'Florence and her treasures (1911) (14743129386)',
        1815,
        'historic',
        'db/images/pipeline_test_set/Q549847_historic.jpg',
        'Firenze aka Florence, Italy (27324370267)',
        1788,
        'frame_included,modern',
        'db/images/pipeline_test_set/Q549847_modern.jpg',
        'PIPELINE-LOST-Q549847',
        'PIPELINE-INV-07',
        'PIPELINE-AUCTION-Q549847',
        '2026-02-07'::date
    ),
    (
        'Q563727',
        'Q563727',
        11,
        uuid_generate_v5(uuid_ns_url(), 'https://smartmatch.invalid/pipeline-seed/lost/Q563727'),
        uuid_generate_v5(uuid_ns_url(), 'https://smartmatch.invalid/pipeline-seed/auction/Q563727'),
        'Hof in Proveis',
        'Herbert Danler',
        '2008',
        2008,
        2008,
        65.0,
        99.5,
        '65 x 99,5 cm',
        'Leinwand',
        'Öl',
        $$Verlustdatensatz: Herbert Danler (Fulpmes 1928 - 2011 Telfs im Stubai), Hof in Proveis. Öl auf Leinwand, 65 x 99,5 cm, 2008. Rechts unten monogrammiert HD; rückseitig am oberen Keilrahmen bezeichnet Hof in Proveis Gampenpaß / Meran Herbert Danler 2008. Provenienz: Privatbesitz Wien.$$,
        $$Auktionsbeschreibung: Hof in Proveis von Herbert Danler, Fulpmes 1928 bis 2011 Telfs im Stubai. Öl auf Leinwand mit den Maßen 65 x 99,5 cm, datiert 2008. Monogramm HD rechts unten; verso auf dem oberen Keilrahmen Hof in Proveis Gampenpaß / Meran Herbert Danler 2008. Aus Privatbesitz Wien.$$,
        'Privatbesitz Wien',
        'Rechts unten monogrammiert: HD; rückseitig am oberen Keilrahmen bezeichnet: Hof in Proveis Gampenpaß / Meran Herbert Danler 2008',
        NULL,
        NULL,
        'Infrared reflectogram of Saint-Anne with the Virgin and Child',
        2375,
        'historic,poor_quality',
        'db/images/pipeline_test_set/Q563727_historic.jpg',
        'Casa mia 21',
        1087,
        'frame_included,modern',
        'db/images/pipeline_test_set/Q563727_modern.jpg',
        'PIPELINE-LOST-Q563727',
        'PIPELINE-INV-08',
        'PIPELINE-AUCTION-Q563727',
        '2026-02-08'::date
    ),
    (
        'Q328079',
        'Q328079',
        12,
        uuid_generate_v5(uuid_ns_url(), 'https://smartmatch.invalid/pipeline-seed/lost/Q328079'),
        uuid_generate_v5(uuid_ns_url(), 'https://smartmatch.invalid/pipeline-seed/auction/Q328079'),
        'Ohne Titel',
        'Hans Bischoffshausen',
        '1963',
        1963,
        1963,
        32.5,
        25.0,
        '32,5 x 25 cm',
        'Papier',
        'Pressung',
        $$Suchmeldung: Hans Bischoffshausen (Feld am See 1927 - 1987 Villach), Ohne Titel. Pressung auf Papier, 32,5 x 25 cm, 1963. Unten mittig signiert und datiert Hans Bischoffshausen 63. Provenienz: Lentos Linz, Privatsammlung Wien.$$,
        $$Kataloglos: Ohne Titel von Hans Bischoffshausen, Feld am See 1927 bis 1987 Villach. Pressung auf Papier, Format 32,5 x 25 cm, datiert 1963. Signatur und Datum unten mittig: Hans Bischoffshausen 63. Herkunft Lentos Linz, danach Privatsammlung Wien.$$,
        'Lentos Linz, Privatsammlung Wien',
        'Unten mittig signiert und datiert: Hans Bischoffshausen 63',
        NULL,
        NULL,
        'Die Gartenlaube (1894) b 824',
        1464,
        'historic',
        'db/images/pipeline_test_set/Q328079_historic.jpg',
        'Sistine Madonna (original)',
        4253,
        'frame_included,modern',
        'db/images/pipeline_test_set/Q328079_modern.jpg',
        'PIPELINE-LOST-Q328079',
        'PIPELINE-INV-09',
        'PIPELINE-AUCTION-Q328079',
        '2026-02-09'::date
    ),
    (
        'Q700251',
        'Q700251',
        14,
        uuid_generate_v5(uuid_ns_url(), 'https://smartmatch.invalid/pipeline-seed/lost/Q700251'),
        uuid_generate_v5(uuid_ns_url(), 'https://smartmatch.invalid/pipeline-seed/auction/Q700251'),
        'Wien',
        'Hans Staudacher',
        '1990',
        1990,
        1990,
        200.0,
        170.0,
        '200 x 170 cm',
        'Leinwand',
        'Öl',
        $$Verlustakte: Hans Staudacher (St. Urban 1923 - 2021 Wien), Wien. Öl auf Leinwand, 200 x 170 cm, 1990. Mittig unten signiert und datiert H. Staudacher Wien 1990; oben mittig ebenfalls 1990 datiert. Provenienz: Ausstellung Steiermark.$$,
        $$Auktionsnotiz: Wien von Hans Staudacher, St. Urban 1923 bis 2021 Wien. Öl auf Leinwand in der Größe 200 x 170 cm, datiert 1990. Signatur und Datierung mittig unten H. Staudacher Wien 1990, zusätzlich oben mittig datiert 1990. Provenienz Ausstellung Steiermark.$$,
        'Ausstellung Steiermark',
        'Mittig unten signiert und datiert: H. Staudacher Wien 1990; oben mittig datiert: 1990',
        NULL,
        NULL,
        'Gemäldegalerie Alte Meister (Dresden) Galeriewerk Braun 1541',
        2030,
        'historic',
        'db/images/pipeline_test_set/Q700251_historic.jpg',
        'Vermeer - Girl reading a letter at a window, Dresden, 2021 Cupid restoration',
        4811,
        'modern',
        'db/images/pipeline_test_set/Q700251_modern.jpg',
        'PIPELINE-LOST-Q700251',
        'PIPELINE-INV-10',
        'PIPELINE-AUCTION-Q700251',
        '2026-02-10'::date
    ),
    (
        'METADATA-ONLY-PRELOG-2011',
        'METADATA-ONLY-PRELOG-2011',
        15,
        uuid_generate_v5(uuid_ns_url(), 'https://smartmatch.invalid/pipeline-seed/lost/METADATA-ONLY-PRELOG-2011'),
        uuid_generate_v5(uuid_ns_url(), 'https://smartmatch.invalid/pipeline-seed/auction/METADATA-ONLY-PRELOG-2011'),
        'Dragens Tag',
        'Drago J. Prelog',
        '2011',
        2011,
        2011,
        100.0,
        120.0,
        '100 x 120 cm',
        'Leinwand',
        'Acryl',
        $$Metadaten-only Suchdatensatz: Drago J. Prelog (Cilli 1939 - 2020 Wien), Dragens Tag. Acryl auf Leinwand, 100 x 120 cm, 2011. Rechts unten signiert und datiert Prelog 2011; rückseitig signiert, datiert, betitelt und mit Größen- und Technikangabe. Provenienz: Ausstellung Steiermark.$$,
        $$Metadaten-only Auktionslos: Dragens Tag von Drago J. Prelog, Cilli 1939 bis 2020 Wien. Acryl auf Leinwand, Maße 100 x 120 cm, datiert 2011. Unten rechts signiert und datiert Prelog 2011; auf der Rückseite erneut signiert, datiert, betitelt sowie mit Technik und Größe versehen. Provenienz Ausstellung Steiermark.$$,
        'Ausstellung Steiermark',
        'Rechts unten signiert und datiert: Prelog 2011; rückseitig signiert, datiert, betitelt und mit Größen- und Technikangabe',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'PIPELINE-LOST-METADATA-PRELOG-2011',
        'PIPELINE-INV-11',
        'PIPELINE-AUCTION-METADATA-PRELOG-2011',
        '2026-02-11'::date
    ),
    (
        'METADATA-ONLY-NEDER-1876',
        'METADATA-ONLY-NEDER-1876',
        16,
        uuid_generate_v5(uuid_ns_url(), 'https://smartmatch.invalid/pipeline-seed/lost/METADATA-ONLY-NEDER-1876'),
        uuid_generate_v5(uuid_ns_url(), 'https://smartmatch.invalid/pipeline-seed/auction/METADATA-ONLY-NEDER-1876'),
        'Streit im Wirtshaus',
        'Johann Michael Neder',
        '1876',
        1876,
        1876,
        27.5,
        39.0,
        '27,5 x 39 cm',
        'Holz',
        'Öl',
        $$Metadaten-only Verlustregister: Johann Michael Neder (Wien 1807 - 1882 Wien), Streit im Wirtshaus. Öl auf Holz, 27,5 x 39 cm, 1876. Rechts unten signiert und datiert Neder 1876. Provenienz: Dorotheum 2007, Privatsammlung Wien.$$,
        $$Metadaten-only Katalogbeschreibung: Streit im Wirtshaus von Johann Michael Neder, Wien 1807 bis 1882 Wien. Öl auf Holz mit den Maßen 27,5 x 39 cm, datiert 1876. Signatur und Datierung rechts unten: Neder 1876. Herkunft Dorotheum 2007 und Privatsammlung Wien.$$,
        'Dorotheum 2007, Privatsammlung Wien',
        'Rechts unten signiert und datiert: Neder 1876',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'PIPELINE-LOST-METADATA-NEDER-1876',
        'PIPELINE-INV-12',
        'PIPELINE-AUCTION-METADATA-NEDER-1876',
        '2026-02-12'::date
    );

INSERT INTO artist (artist_id, complete_name, raw_data)
SELECT DISTINCT ON (artist_full_name)
    uuid_generate_v5(uuid_ns_url(), 'https://smartmatch.invalid/pipeline-seed/artist/' || artist_full_name),
    artist_full_name,
    jsonb_build_object(
        'seed_source', 'pipeline_integrity_metadata_fixture',
        'metadata_testset_row', metadata_testset_row,
        'seed_key', seed_key
    )::text
FROM pipeline_seed_pair
ORDER BY artist_full_name, metadata_testset_row
ON CONFLICT (artist_id) DO UPDATE SET
    complete_name = EXCLUDED.complete_name,
    raw_data = EXCLUDED.raw_data;

INSERT INTO lost_artwork (
    lost_artwork_id,
    title,
    artist_ids,
    width,
    height,
    dating,
    dating_start,
    dating_end,
    description,
    inventory_number,
    material,
    technique,
    provenance,
    circumstances_of_loss,
    lost_art_id,
    lost_art_url,
    keywords,
    type_of_loss,
    restituted,
    raw_data
)
SELECT
    lost_artwork_id,
    title,
    ARRAY[
        uuid_generate_v5(uuid_ns_url(), 'https://smartmatch.invalid/pipeline-seed/artist/' || artist_full_name)
    ]::uuid[],
    width_cm,
    height_cm,
    dating,
    dating_start,
    dating_end,
    lost_description,
    inventory_number,
    material,
    technique,
    provenance,
    CASE
        WHEN lost_image_path IS NULL THEN 'Recorded as missing in a metadata-only SmartMatch seed scenario.'
        ELSE 'Recorded as missing in a SmartMatch seed scenario with a linked historic reference image.'
    END,
    lost_art_id,
    'https://example.invalid/smartmatch/lost/' || seed_key,
    ARRAY['pipeline-seed', 'metadata-matching', class_label, artist_full_name, title]::text[],
    'Pipeline validation seed',
    false,
    jsonb_strip_nulls(jsonb_build_object(
        'seed_source', 'pipeline_integrity_metadata_fixture',
        'image_seed_source', 'db/images/pipeline_test_set',
        'metadata_testset_row', metadata_testset_row,
        'class_label', class_label,
        'role', 'lost',
        'description_variant', 'wording-mixed-lost',
        'artist_full_name', artist_full_name,
        'dimensions_raw_data', dimensions_label,
        'source_file_id', lost_source_file_id,
        'source_image_file_class_id', lost_source_image_file_class_id,
        'source_tags', lost_source_tags,
        'seed_image_path', lost_image_path,
        'has_seed_image', lost_image_path IS NOT NULL
    ))
FROM pipeline_seed_pair
ON CONFLICT (lost_artwork_id) DO UPDATE SET
    title = EXCLUDED.title,
    artist_ids = EXCLUDED.artist_ids,
    width = EXCLUDED.width,
    height = EXCLUDED.height,
    dating = EXCLUDED.dating,
    dating_start = EXCLUDED.dating_start,
    dating_end = EXCLUDED.dating_end,
    description = EXCLUDED.description,
    inventory_number = EXCLUDED.inventory_number,
    material = EXCLUDED.material,
    technique = EXCLUDED.technique,
    provenance = EXCLUDED.provenance,
    circumstances_of_loss = EXCLUDED.circumstances_of_loss,
    lost_art_id = EXCLUDED.lost_art_id,
    lost_art_url = EXCLUDED.lost_art_url,
    keywords = EXCLUDED.keywords,
    type_of_loss = EXCLUDED.type_of_loss,
    restituted = EXCLUDED.restituted,
    raw_data = EXCLUDED.raw_data;

INSERT INTO auction_artwork (
    auction_artwork_id,
    normalised_version,
    title,
    artist_id,
    artist_full_name,
    width,
    height,
    dating,
    dating_start,
    dating_end,
    description,
    auction_details,
    material,
    technique,
    provenance,
    auction_date,
    lot_id,
    lot_url,
    condition,
    signature,
    literature,
    raw_data,
    artist_raw_data,
    dimensions_raw_data,
    is_metadata_matching_processed,
    is_metadata_extraction_processed
)
SELECT
    auction_artwork_id,
    1,
    NULL::text,
    NULL::uuid,
    NULL::varchar(255),
    NULL::real,
    NULL::real,
    NULL::varchar(255),
    NULL::smallint,
    NULL::smallint,
    auction_description,
    jsonb_build_object(
        'sale_title', 'SmartMatch Pipeline Seed Sale',
        'lot_number', lot_id,
        'metadata_testset_row', metadata_testset_row,
        'estimate', '1000-1500 EUR',
        'currency', 'EUR'
    ),
    NULL::varchar(255),
    NULL::varchar(255),
    NULL::text,
    auction_date,
    lot_id,
    'https://example.invalid/smartmatch/auction/' || seed_key,
    NULL::text,
    NULL::text,
    NULL::text,
    jsonb_strip_nulls(jsonb_build_object(
        'seed_source', 'pipeline_integrity_metadata_fixture',
        'image_seed_source', 'db/images/pipeline_test_set',
        'metadata_testset_row', metadata_testset_row,
        'class_label', class_label,
        'role', 'auction',
        'description_variant', 'wording-mixed-auction',
        'source_file_id', auction_source_file_id,
        'source_image_file_class_id', auction_source_image_file_class_id,
        'source_tags', auction_source_tags,
        'seed_image_path', auction_image_path,
        'has_seed_image', auction_image_path IS NOT NULL
    )),
    NULL::text,
    NULL::text,
    false,
    false
FROM pipeline_seed_pair
ON CONFLICT (auction_artwork_id) DO UPDATE SET
    normalised_version = EXCLUDED.normalised_version,
    title = EXCLUDED.title,
    artist_id = EXCLUDED.artist_id,
    artist_full_name = EXCLUDED.artist_full_name,
    width = EXCLUDED.width,
    height = EXCLUDED.height,
    dating = EXCLUDED.dating,
    dating_start = EXCLUDED.dating_start,
    dating_end = EXCLUDED.dating_end,
    description = EXCLUDED.description,
    auction_details = EXCLUDED.auction_details,
    material = EXCLUDED.material,
    technique = EXCLUDED.technique,
    provenance = EXCLUDED.provenance,
    auction_date = EXCLUDED.auction_date,
    lot_id = EXCLUDED.lot_id,
    lot_url = EXCLUDED.lot_url,
    condition = EXCLUDED.condition,
    signature = EXCLUDED.signature,
    literature = EXCLUDED.literature,
    raw_data = EXCLUDED.raw_data,
    artist_raw_data = EXCLUDED.artist_raw_data,
    dimensions_raw_data = EXCLUDED.dimensions_raw_data,
    is_metadata_matching_processed = false,
    is_metadata_extraction_processed = false;

WITH seed_image_path AS (
    SELECT lost_image_path AS file_path
    FROM pipeline_seed_pair
    WHERE lost_image_path IS NOT NULL
    UNION
    SELECT auction_image_path AS file_path
    FROM pipeline_seed_pair
    WHERE auction_image_path IS NOT NULL
)
INSERT INTO image_file (file_path)
SELECT seed_image_path.file_path
FROM seed_image_path
WHERE NOT EXISTS (
    SELECT 1
    FROM image_file existing
    WHERE existing.file_path = seed_image_path.file_path
);

INSERT INTO lost_artwork_image_file (lost_artwork_id, image_file_id)
SELECT
    seed.lost_artwork_id,
    image.image_file_id
FROM pipeline_seed_pair seed
JOIN LATERAL (
    SELECT image_file_id
    FROM image_file
    WHERE file_path = seed.lost_image_path
    ORDER BY image_file_id
    LIMIT 1
) image ON true
WHERE seed.lost_image_path IS NOT NULL
ON CONFLICT (lost_artwork_id, image_file_id) DO NOTHING;

INSERT INTO auction_artwork_image_file (
    auction_artwork_id,
    image_file_id,
    is_image_matching_processed
)
SELECT
    seed.auction_artwork_id,
    image.image_file_id,
    false
FROM pipeline_seed_pair seed
JOIN LATERAL (
    SELECT image_file_id
    FROM image_file
    WHERE file_path = seed.auction_image_path
    ORDER BY image_file_id
    LIMIT 1
) image ON true
WHERE seed.auction_image_path IS NOT NULL
ON CONFLICT (auction_artwork_id, image_file_id) DO UPDATE SET
    is_image_matching_processed = false;

DROP TABLE pipeline_seed_pair;
